#!/bin/bash

# These commands take this form
# ./ops [script] [option]

script=${1}
option=${2}

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "start" ] ; then
  docker-compose -f docker/dev.yml up

elif [ $script == "stop" ] ; then
  docker-compose -f docker/dev.yml down
elif [ $script == "commitship" ] ; then
  git add .
  git commit -m "$2"
  git push origin master
  ./ops ship
elif [ $script == "ship" ] ; then
  echo "Building Static Webpage..."
  npm run build
  echo "Uploading './build' to Droplet..."
  scp -prq ./build/. root@162.243.131.60:/usr/share/nginx/html/Portfolio-App
  echo "Uploading './api' to Droplet"
  scp -prq ./api/. root@162.243.131.60:/api
fi