#!/bin/bash

# These commands take this form
# ./ops [script] [option]

script=${1}
option=${2}

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "start" ] ; then
  docker-compose -f docker/dev.yml up

elif [ $script == "stop" ] ; then
  docker-compose -f docker/dev.yml down
elif [ $script == "commitship" ] ; then
  git add .
  git commit -m "$2"
  git push origin master
  ./ops ship
elif [ $script == "ship" ] ; then
    echo "Shipping to production...";
    ssh root@192.241.229.157 "cd Portfolio-App && git pull origin master"
fi